directory: ~/fs
applications:
  go:
    tagged:
      repository: "https://github.com/golang/go"
      download: "https://go.dev/dl/{{ $.Tag }}.linux-amd64.tar.gz"
      filters: 
        - "refs/tags/weekly"
        - "refs/tags/release"
        - "[0-9]rc[0-9]"
    deploy:
      - files:
          - "bin/go"
        destination: "~/bin"
  lockbox:
    branch:
      project: "seanenck/lockbox"
      branch: "master"
  rg:
    github:
      project: "BurntSushi/ripgrep"
      asset: "x86_64-unknown-linux-(.+?).tar.gz$"
    deploy:
      - files:
          - "rg"
        destination: "~/bin"
  nvim:
    github:
      project: "neovim/neovim"
      asset: "nvim-linux64.tar.gz$"
    deploy:
      - files:
          - "bin/nvim"
        destination: "~/bin"
  blap:
    github:
      project: "seanenck/blap"
      asset: "tarball"
    build:
      - command: ["make", "VERSION={{ $.Tag }}"]
    deploy:
      - files:
          - "build/blap"
        destination: "~/.local/bin/development"
