disable: true
applications:
  go:
    git:
      repository: "https://github.com/golang/go"
      tagged:
        download: "https://go.dev/dl/{{ $.Vars.Tag }}.linux-amd64.tar.gz"
        filters: 
          - "refs/tags/weekly"
          - "refs/tags/release"
          - "[0-9]rc[0-9]"
    deploy:
      - files:
          - "bin/go"
        destination: "~/bin"
  rg:
    github:
      project: "BurntSushi/ripgrep"
      release:
        asset: "x86_64-unknown-linux-(.+?).tar.gz$"
    deploy:
      - files:
          - "rg"
        destination: "~/bin"
